In [ ]:
sum = 0
count = 1
while count <= 10:
    sum = sum + count
    count = count + 1
print('1+2+3+4+5+...+10=',sum)

In [ ]:
x=10000
year=0
while x<20000:
    year+=1
    x=x*1.0184
print(str(year),'年後,存款金額加倍')

In [ ]:
id='pow'
pwd='123'
while True:
    x=input('請輸入帳號')
    y=input('請輸入密碼')
    if(x==id and y==pwd):
        print('歡迎登入')
        break
    else:
        print('帳號/密碼輸入錯誤')

In [ ]:
mylist=['a','b','c','d']
for i in mylist:
    if i=='c':
        break
    else:
        print(i)    

In [ ]:
import random
for i in fange(0,10):
    oprint(random.randim())

In [ ]:
for i in range(0,10):
    print(radom.randint(1,9))

In [2]:
import random
number=random.randint(1,99)
while True:
    gess=input('請輸入1-99的數字(q離開):')
    if guess -- 'q':
        print('離開遊戲,正確數字是',number)
        break
    else:
            if number==intguess():
                print('恭喜,猜對了')
                break
            else:
                print('猜錯了')
                
                    

請輸入1-99的數字(q離開):q


NameError: name 'guess' is not defined

In [3]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [6]:
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)

[ 3  6  9 12 15]


In [7]:
print(type(a_ndarray))
print(a_ndarray.ndim)
print(a_ndarray.shape)
print(a_ndarray.dtype)

<class 'numpy.ndarray'>
1
(5,)
int32


In [9]:
z=np.zeros(6)
print(z)
print(np.zeros((2,6)))
print(np.empty((2,6,2)))
print(np.arange(10))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[ 1.91295334e+214  1.32971156e-152]
  [ 2.44835942e+198  1.05894329e-153]
  [ 8.78411391e+247 -2.94579173e-311]
  [ 1.96086573e+243  6.01334434e-154]
  [ 9.87762528e+247  4.46811730e-091]
  [ 2.44041296e-154 -3.49326655e-311]]

 [[ 5.03927630e+180  3.81187276e+180]
  [ 7.74412839e+228  2.59345433e+161]
  [ 1.99416198e+174 -4.01739915e-311]
  [ 1.32884243e+179  2.32160957e-152]
  [ 1.81263939e-152  2.66065731e-260]
  [ 7.70858946e+218 -4.36752862e-311]]]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [13]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])
print(my_2d_array[:,1])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [30]:
groups=["Modern","DevOps","Cloud","Big Data","Securlity","自我挑戰組"]
ironman=[56,8,19,14,6,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern' 'DevOps' 'Cloud' 'Big Data' 'Securlity' '自我挑戰組']
[56  8 19 14  6 71]


In [31]:
print(ironman_array >= 10)
print(groups_array[ironman_array >= 10])
print(groups_array!="自我挑戰組")
print(ironman_array[groups_array!="自我挑戰組"])

[ True False  True  True False  True]
['Modern' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


In [33]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [34]:
print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [15]:
nan_array=np.array([56,8,19,14,6,np.nan])
print(nan_array)

NameError: name 'np' is not defined

In [10]:
import pandas as pd
groups = ["Modern Web","DevOps","Cloub","Big Data","Security","自我挑戰組"]
ironmen = [59,9,19,14,6,77]
ironmen_dict={
             "groups":groups,
             "ironmen":ironmen
}
ironmen_df=pd.DataFrame(ironmen_dict)
ironmen_df

groups  ironmen
0  Modern Web       59
1      DevOps        9
2       Cloub       19
3    Big Data       14
4    Security        6
5       自我挑戰組       77

In [14]:
print(ironmen_df.ndim)
print(ironmen_df.shape)
print(ironmen_df.dtypes)

2
(6, 2)
groups     object
ironmen     int64
dtype: object


In [16]:
print(ironmen_df.sum())
print(ironmen_df.ironmen.sum())
print(ironmen_df.mean)
print(ironmen_df.median)
print(ironmen_df.describe())

groups     Modern WebDevOpsCloubBig DataSecurity自我挑戰組
ironmen                                           184
dtype: object
184
<bound method DataFrame.mean of        groups  ironmen
0  Modern Web       59
1      DevOps        9
2       Cloub       19
3    Big Data       14
4    Security        6
5       自我挑戰組       77>
<bound method DataFrame.median of        groups  ironmen
0  Modern Web       59
1      DevOps        9
2       Cloub       19
3    Big Data       14
4    Security        6
5       自我挑戰組       77>
         ironmen
count   6.000000
mean   30.666667
std    29.803803
min     6.000000
25%    10.250000
50%    16.500000
75%    49.000000
max    77.000000


In [17]:
import pandas as pd
groups = ["Modern Web","DevOps","Cloub","Big Data","Security","自我挑戰組"]
ironmen = [59,9,19,14,6,77]
ironmen_dict={
             "groups":groups,
             "ironmen":ironmen
}
ironmen_df=pd.DataFrame(ironmen_dict)
print(ironmen_df.loc[:,"groups"].isnull())
print(ironmen_df.loc[:,"ironmen"].notnull())

0    False
1    False
2    False
3    False
4    False
5    False
Name: groups, dtype: bool
0    True
1    True
2    True
3    True
4    True
5    True
Name: ironmen, dtype: bool


In [21]:
a=ironmen_df.dropna()
b=ironmen_df.fillna(0)
c=ironmen_df.ironmen.fillna(ironmen_df.ironmen.mean())

In [20]:
b=ironmen_df.fillna(0)
b

groups  ironmen
0  Modern Web       59
1      DevOps        9
2       Cloub       19
3    Big Data       14
4    Security        6
5       自我挑戰組       77

In [22]:
import pandas as pd
groups = ["Modern Web","DevOps","Cloub","Big Data","Security","自我挑戰組"]
ironmen = [59,9,19,14,6,77]
ironmen_dict={
             "groups":groups,
             "ironmen":ironmen
}
ironmen_df=pd.DataFrame(ironmen,columns=["ironmen"],index=groups)
ironmen_df.sort_index()

ironmen
Big Data         14
Cloub            19
DevOps            9
Modern Web       59
Security          6
自我挑戰組            77

In [13]:
import pandas as pd
url="http://storage.googleapis.com/2017_ithome_ironman/data/iris.csv"
iris_df=pd.read_csv(url)
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
iris_df.mean()

Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [15]:
iris_df['Sepal.Length'].median()

5.8

In [16]:
import pandas as pd
iris_df=pd.read_csv('iris.csv')
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
import pandas as pd
url="http://storage.googleapis.com/2017_ithome_ironman/data/iris.xlsx"
iris_df=pd.read_excel(url)
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
import math

def circle(radius):
    area=radius=radius=math.pi
    return area

print(circle(10))

3.141592653589793


In [31]:
import math

def circle(radius):
    area=radius*radius*math.pi
    return area
r=input("請輸入圓的半徑")
print("圓面積為:",circle(float(r)))

請輸入圓的半徑12
圓面積為: 452.3893421169302


In [33]:
import random
def exchange_sort(input_list):
    a=input_list
    for i in range(0,len(input_list)-1):
        for j in range(i+1,len(input_list)):
            if a[i]>a[j]:
                a[i],a[j]=a[j],a[i]
    return a

my_vector = random.sample(range(0,100),10)
print(my_vector)
print(exchange_sort(my_vector))

[2, 37, 81, 39, 50, 29, 85, 91, 70, 27]
[2, 27, 29, 37, 39, 50, 70, 81, 85, 91]
